require("kento.plugins-setup")
require("kento.core.colorscheme")
require("kento.core.keymaps")
require("kento.core.options")
require("kento.plugins.nvim-tree")
require("kento.plugins.lualine")
require("kento.plugins.telescope")
