theme = "tokyonight"

[editor]
bufferline="multiple"

[editor.cursor-shape]
insert= "bar"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.statusline]
left = ["mode","selections", "version-control"]
center = ["file-name"]
right = ["diagnostics","position", "position-percentage", "file-encoding", "file-line-ending", "file-type", "spinner"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true
