[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
format = true
codeActionsOnSave = { mode = "all", "source.fixAll.eslint" = true }
nodePath = ""
quiet = false
rulesCustomizations = []
run = "onType"
useESLintClass = false
validate = "on"
experimental = {}
problems = { shortenToSingleLine = false }
workingDirectory = { mode = "auto" }

[language-server.eslint.config.codeAction]
disableRuleComment = { enable = true, location = "separateLine" }
showDocumentation = { enable = true }

[language-server.efm-lsp-prettier]
command = "efm-langserver"

[language-server.efm-lsp-prettier.config]
documentFormatting = true
languages = { typescript = [ { formatCommand = "prettier --stdin-filepath ${INPUT} --parser typescript", formatStdin = true}], javascript = [ { formatCommand = "prettier-eslint --stdin ${INPUT} --parser typescript", formatStdin = true}]}

[[language]]
name = "javascript"
auto-format = false
# formatter = {command = "prettier-eslint", args = ["--parser", "typescript"]}
# formatter = { command = "dprint", args = [ "fmt", "--stdin", "javascript", "--config", "~/.config/dprint.json"] }
language-servers = [ 
  { name = "typescript-language-server", except-features=["format"]},
  "eslint",
  # "efm-lsp-prettier",
]

[[language]]
name = "typescript"
auto-format = false
formatter = {command = "prettier", args = ["--parser", "typescript"]}
# formatter = { command = "dprint", args = [ "fmt", "--stdin", "javascript", "--config", "~/.config/dprint.json"] }
language-servers = [ 
  { name = "typescript-language-server", except-features=["format"]},
  "eslint",
  # "efm-lsp-prettier",
]

[[language]]
name = "tsx"
# auto-format = true
formatter = {command = "prettier", args = ["--parser", "typescript"]}
# formatter = { command = "dprint", args = [ "fmt", "--stdin", "javascript", "--config", "~/.config/dprint.json"] }
language-servers = [ 
  { name = "typescript-language-server", except-features=["format"]},
  "eslint",
  "efm-lsp-prettier",
]

[[language]]
name = "jsx"
# auto-format = true
formatter = {command = "prettier", args = ["--parser", "typescript"]}
# formatter = { command = "dprint", args = [ "fmt", "--stdin", "javascript", "--config", "~/.config/dprint.json"] }
language-servers = [ 
  { name = "typescript-language-server" },
  "eslint",
  "efm-lsp-prettier",
]

[[language]]
name = "python"
scope = "source.python"
language-servers = [ "ruff-lsp" ]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "rust"
auto-format = true
